Add Algolia
zachflower/awesome-open-source-supporters pull request #5
Opened 2017-10-19 01:26 UTC by Haroenv

I was doubting to add `requires-approval` or not, because default free plan is 10k records, 100k ops; default OSS is 50k / 100k and more needs approval but is definitely possible. Docsearch is also always free for OSS

Thank you for taking the time to work on a PR for Awesome-Open-Source-Supporters!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines: ``[Company Name](link) `tag` - description``
- [ ] Your additions are ordered alphabetically.
- [ ] Your additions are commercial software that offer their services for free to Open Source projects.
- [ ] Your additions contain any relevant tags: `requires-approval`
- [ ] You have searched the repository for any relevant issues or PRs.
- [ ] Any category you are creating has the minimum requirement of 2 items.

2017-10-20 02:56 UTC, zachflower requested changes

2017-10-20 02:56 UTC, zachflower commented on README.md
> +- [Algolia](https://www.algolia.com) - Search as a service API
Thanks for the submission! I had no idea Algolia offered an OSS tier! While they do have a free tier, their Open Source specific one does require approval, so I think a `requires-approval` tag is appropriate here.

2017-10-20 17:18 UTC, Haroenv commented
updated @zachflower

2017-10-22 05:28 UTC, zachflower commented
Looks good, thanks!

2017-10-22 05:28 UTC, merged

2017-10-23 09:01 UTC, dzello commented
@Haroenv small correction, the [Algolia for Open Source plan](https://www.algolia.com/for-open-source) is 100k records and 200k ops by default.