Add Transloadit
zachflower/awesome-open-source-supporters pull request #7
Opened 2017-10-20 13:14 UTC by kvz

- [x] Your submissions are formatted according to the guidelines: ``[Company Name](link) `tag` - description``
- [x] Your additions are ordered alphabetically.
- [x] Your additions are commercial software that offer their services for free to Open Source projects.
- [x] Your additions contain any relevant tags: `requires-approval`
- [x] You have searched the repository for any relevant issues or PRs.

2017-10-22 05:26 UTC, zachflower requested changes
Great submission! Just one small change.

2017-10-22 05:26 UTC, zachflower commented on README.md
> +- [Transloadit](https://transloadit.com/) `requires-approval` - API for file uploading & encoding. Creators of [uppy.io](https://uppy.io) and [tus.io](https://tus.io).
Would you please remove the `Creators of uppy.io and tus.io.`? They're awesome projects, they just don't fit within the criteria of the list.

2017-10-23 12:20 UTC, kvz commented
Sure, fixed! 👌

2017-10-23 14:44 UTC, zachflower approved these changes

2017-10-23 14:45 UTC, merged